### ISSUE TITLE
Username and password input Bug

### ISSUE THREAD

**Issue by VnHunter95** [VnHunter95/DoAnMonCCVMTPTPM#6]
Có thể input "asd' ;" hoặt "Admin' or 1=1;" vào và không báo lỗi
Nguyên do: 
Dòng result = TK.LoadTaiKhoanTheoTenVaMatKhau(taiKhoan, matKhau);
Chạy trước khi dữ liệu input.

**Comment by VnHunter95** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Bug] Issue 1](https://trello.com/c/ZvWCNel0/13-bug-issue-1)

**Comment by Thanhtt0405** [comment]
Ok

Vào 27-12-2016 10:59, "VnHunter95" <notifications@github.com> đã viết:
